name: Deploy blog to GitHub Pages

on:
  push:
    branches: [main]

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: taiki-e/install-action@v2
      with:
        tool: zola@latest

    # - uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/zola
    #     key: zola-${{ runner.os }}-${{ github.sha }}
    #     restore-keys: zola-${{ runner.os }}-

    - name: Build site
      run: zola build       # 输出目录默认为 public/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        folder: public

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

